# Generated by Django 4.1.5 on 2024-05-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimagecase',
            name='userPrompt',
        ),
    ]
