# Generated by Django 5.0.6 on 2024-05-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0002_remove_userimagecase_userprompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimagecase',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userimagecase',
            name='resultPrompt',
            field=models.TextField(null=True),
        ),
    ]
