# Generated by Django 5.0.6 on 2024-05-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0003_alter_userimagecase_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimagecase',
            name='image_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
